name: nCombat
version: '${project.version}'
main: me.pog5.ncombat.NCombat
description: A Simple yet efficient CombatLog prevention plugin
commands:
  ncombat:
    description: Manage nCombat
    usage: /ncombat [bypass/toggle]
    permission: ncombat
permissions:
  ncombat:
    children:
      ncombat.bypass:
        description: Permission to bypass the plugin entirely.
        default: op
      ncombat.toggle:
        description: Disable or enable CombatLog serverwide.
        default: op